# Generated by Django 5.2 on 2025-11-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_passenger_id_number_booking_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='passenger_id_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
    ]
